const skisArray = [
  {
    "resourceId": "47aaf4dd-5298-4e1e-991c-7552297da3d2",
    "productResourceId": "47aaf4dd-5298-4e1e-991c-7552297da3d2",
    "productName": "(Size 28.5) Nordica Sportmachine 90 R",
    "blurb": "(Size 28.5) Nordica Sportmachine 90 R - Unisex",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "950a4e12-3521-47cd-a64b-6ee8404b558b",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/dc359f7d-6b72-4c7f-9750-d73e42a88d5a_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Boots",
    "productSubsubcategoryName": "Unisex",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "16379db3-4f0c-413a-9878-a143850433f5",
    "productResourceId": "16379db3-4f0c-413a-9878-a143850433f5",
    "productName": "(Size: 29.5) Nordica Sportmachine 90 R",
    "productRating": 0.0,
    "blurb": "(Size: 29.5) Nordica Sportmachine 90 R - Unisex",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "43860bc6-d0ef-443d-ab67-bd19f84e1c0c",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/f9eeae1d-2382-41dc-b2e8-4abca1de2d28_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Boots",
    "productSubsubcategoryName": "Unisex",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "0423fd78-bfb2-46f5-a167-af6bb80a1c58",
    "productResourceId": "0423fd78-bfb2-46f5-a167-af6bb80a1c58",
    "productName": "(Size: 26.5) Nordica Sportmachine 90 R",
    "productRating": 0.0,
    "blurb": "(Size: 26.5) Nordica Sportmachine 90 R - Unisex",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "f1b1fb3c-16e8-4263-8f03-156cb564f328",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/64a0b76a-37c4-42bf-b1d4-6f084a9ef947_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Boots",
    "productSubsubcategoryName": "Unisex",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "a2b89e94-e07b-469a-805a-c647b3f0b9c0",
    "productResourceId": "a2b89e94-e07b-469a-805a-c647b3f0b9c0",
    "productName": "(Size 27.5) Nordica Sportmachine 90 R",
    "productRating": 0.0,
    "blurb": "(Size 27.5) Nordica Sportmachine 90 R - Unisex",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "f7c2b2c1-e823-4be2-a4c7-e46d620cf26b",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/a71b4565-a75f-4359-ab0b-5c574ec7fb13_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Boots",
    "productSubsubcategoryName": "Unisex",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "96cbb943-6175-4887-b7d1-a9f868c7f658",
    "productResourceId": "96cbb943-6175-4887-b7d1-a9f868c7f658",
    "productName": "(Size: 24.5) Nordica Sportmachine 75 WR",
    "productRating": 0.0,
    "blurb": "(Size: 24.5) Nordica Sportmachine 75 WR",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "c5bd8302-daf5-4235-82a4-f243dfbe653b",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/98aead73-34e6-4a78-ba99-5cd5263e741c_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Boots",
    "productSubsubcategoryName": "Womens",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "202b09a5-2ace-4e46-bb7a-62f6d6747c82",
    "productResourceId": "202b09a5-2ace-4e46-bb7a-62f6d6747c82",
    "productName": "(Size: 26.5) Nordica Sportmachine 75 WR",
    "productRating": 0.0,
    "blurb": "(Size: 26.5) Nordica Sportmachine 75 WR - Womens",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "1e3d25d3-8c00-48c1-a1be-27513ec19dca",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/e7820c82-dfab-4a01-9322-2449b4b59fae_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Boots",
    "productSubsubcategoryName": "Womens",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "00245a88-7f74-40b9-807e-9e04007c1cfe",
    "productResourceId": "00245a88-7f74-40b9-807e-9e04007c1cfe",
    "productName": "(Size: 22.5) Nordica Sportmachine 75 WR",
    "productRating": 0.0,
    "blurb": "(Size: 22.5) Nordica Sportmachine 75 WR - Womens",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "4867e7e0-4e50-4d82-9dc6-982edadf672c",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/344cd05d-c882-4a2b-b131-19e5b6084243_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Boots",
    "productSubsubcategoryName": "Womens",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "c5084186-b0c5-4dc1-ac26-89f65bce6a7e",
    "productResourceId": "c5084186-b0c5-4dc1-ac26-89f65bce6a7e",
    "productName": "(Size: 23.5) Nordica Sportmachine 75 WR",
    "productRating": 0.0,
    "blurb": "(Size: 23.5) Nordica Sportmachine 75 WR - Womens",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "e001d151-5d36-4e02-b268-d195b3646781",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/24d9d87a-4386-4586-b43a-75bea1f2ccb3_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Boots",
    "productSubsubcategoryName": "Womens",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "f0ed300c-03a0-45ec-b8b7-8d840e5a95d3",
    "productResourceId": "f0ed300c-03a0-45ec-b8b7-8d840e5a95d3",
    "productName": "Nordica All Drive 76 (Length: 142)",
    "productRating": 0.0,
    "blurb": "Nordica All Drive 76 (Length: 142)",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "c619e91d-f9ba-4c68-9b0c-2f7765a5fd58",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/635e3bb8-f7f8-44a6-ba91-c982f6c64fc4_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Ski",
    "productSubsubcategoryName": "",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "9470875f-4bd8-408c-a0be-958c8056604c",
    "productResourceId": "9470875f-4bd8-408c-a0be-958c8056604c",
    "productName": "Nordica All Drive 76 (Length: 158)",
    "productRating": 0.0,
    "blurb": "Nordica All Drive 76 (Length: 158)",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "3a1ab86d-efbb-42d2-9f4e-f67c302689cb",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/2e401fc0-9455-4a54-8854-3b2ee9bd5eb5_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Ski",
    "productSubsubcategoryName": "",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "d913c641-f60a-48f4-95f6-7d578830396f",
    "productResourceId": "d913c641-f60a-48f4-95f6-7d578830396f",
    "productName": "Nordica All Drive 76 (Length: 150)",
    "productRating": 0.0,
    "blurb": "Nordica All Drive 76 (Length: 150)",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "9a21c5c9-dcfc-4d0c-8edb-7e85ee1b04d5",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/90dc2990-d5b0-40cd-966b-1bde9e17a529_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Ski",
    "productSubsubcategoryName": "",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "61e5f145-f876-419b-93c2-8780108ac041",
    "productResourceId": "61e5f145-f876-419b-93c2-8780108ac041",
    "productName": "Nordica All Drive 76 (Length: 166)",
    "productRating": 0.0,
    "blurb": "Nordica All Drive 76 (Length: 166)",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "d59321d6-5c21-4fa1-aedf-a31398e67dd0",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/18755c77-311f-4c31-af8e-f3c4ff8e852b_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Ski",
    "productSubsubcategoryName": "",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  },
  {
    "resourceId": "6ca0d1de-0107-4884-a90e-f86f096926dd",
    "productResourceId": "6ca0d1de-0107-4884-a90e-f86f096926dd",
    "productName": "Nordica All Drive 76 (Length: 136)",
    "productRating": 0.0,
    "blurb": "Nordica All Drive 76 (Length: 136)",
    "isBundle": false,
    "inBundle": true,
    "hasRegionalPricing": false,
    "displayOrder": 0,
    "productPhotos": [
      {
        "resourceId": "53efb571-10b2-401e-8d75-cfd3e03efe64",
        "caption": "",
        "file": "https://skiptidevstorage.blob.core.windows.net/images/659729f4-aab5-4817-bd1c-85df2091d207_thumb.jpg",
        "displayOrder": 10,
        "resourceType": 0,
        "photoType": 6,
        "heightPixels": 0,
        "widthPixels": 0
      }
    ],
    "ownerDisplayName": "",
    "ownerAvatar": "",
    "numberOfReviews": 0,
    "productCategory": 0,
    "productCategoryName": "Sports",
    "productSubcategoryName": "Ski",
    "productSubsubcategoryName": "",
    "isFeatured": false,
    "experienceId": 0,
    "pricingLabel": "",
    "isActive": true,
    "votesToAcquire": 0,
    "chooseMinimum": 1,
    "chooseMaximum": 1,
    "basePerDayUsd": 0.0,
    "basePerWeekUsd": 0.0
  }
];

export default skisArray;